name: Ruby on Rails

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.0.0, 5.2.3, 6.0.0, 6.1.0, master]
        ruby_version: [2.4.10, 2.5.8, 2.6.6, 2.7.2, 3.0.0]
        exclude:
          - rails_version: 5.0.0
            ruby_version: 3.0.0
          - rails_version: 5.2.3
            ruby_version: 3.0.0
          - rails_version: 6.0.0
            ruby_version: 3.0.0
          - rails_version: 6.0.0
            ruby_version: 2.4.10
          - rails_version: 6.1.0
            ruby_version: 2.4.10
          - rails_version: master
            ruby_version: 2.4.10
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Update rubygems when testing with Ruby 2.4.x
      if: startsWith(matrix.ruby_version, '2.4')
      run: |
        gem update --system --no-document
    - name: Build and test with Rake
      run: |
        gem install bundler:1.17.3
        bundle update
        bundle install --jobs 4 --retry 3
        bundle exec rake
        bundle exec rubocop
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
